package id.laris.assistant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MoviesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoviesAllPropertiesEquals(Movies expected, Movies actual) {
        assertMoviesAutoGeneratedPropertiesEquals(expected, actual);
        assertMoviesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoviesAllUpdatablePropertiesEquals(Movies expected, Movies actual) {
        assertMoviesUpdatableFieldsEquals(expected, actual);
        assertMoviesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoviesAutoGeneratedPropertiesEquals(Movies expected, Movies actual) {
        assertThat(expected)
            .as("Verify Movies auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoviesUpdatableFieldsEquals(Movies expected, Movies actual) {
        assertThat(expected)
            .as("Verify Movies relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getGenres()).as("check genres").isEqualTo(actual.getGenres()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoviesUpdatableRelationshipsEquals(Movies expected, Movies actual) {
        // empty method
    }
}
