# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: larischatbotassistant
services:
  app:
    image: larischatbotassistant
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgresql:5432/larisChatbotAssistant
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/larisChatbotAssistant
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
